# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  # Disable checking updates for faster testing
  config.vm.box_check_update = false
  config.vbguest.auto_update = false  if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.network 'private_network', ip: '10.10.10.10'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.synced_folder "files", "/home/vagrant/files", type: 'rsync',
    rsync__args: [
      "--archive",
      "--delete",
      "--force",
      "--numeric-ids"
    ],
    rsync__exclude: [
      "/excluded_file.txt",
      "/excluded_directory",
      "excluded_nested_file.txt",
      "excluded_nested_directory",
      "*.not",
      ".git"
    ],
    rsync__rsync_path: 'rsync',
    rsync__verbose: true

  config.ssh.username = 'vagrant'
  config.ssh.forward_agent = true


  # Vagrant rsyncer settings are introduced below with their default values.

  # How often (in seconds) to read file system events
  config.syncer.interval = 0.2

  # Whether or not to start watching after the machine is up, reloaded or resumed
  config.syncer.run_on_startup = false

  # Whether or not to show the file system events
  config.syncer.show_events = false

  # Optional SSH arguments passed to rsync for lower CPU load
  config.syncer.ssh_args = [
    '-o StrictHostKeyChecking=no',
    '-o IdentitiesOnly=true',
    '-o UserKnownHostsFile=/dev/null',
    '-c arcfour,blowfish-cbc',
    '-o Compression=no',
    '-x'
  ]
end
